#include "sidecar_views.h"

#include "sqlite_support.h"

namespace traceloom::compat {

#if defined(TRACELOOM_NATIVE_HAS_SQLITE_COMPAT)

void materialize_tree_node_anchor_view(SqliteDb& db) {
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_tree_node_anchor AS "
      "SELECT "
      "na.node_id, "
      "n.local_node_id, "
      "na.anchor_id, "
      "na.db_idx, "
      "na.device_id, "
      "na.view_name, "
      "na.occurrence_idx, "
      "na.anchor_order, "
      "na.coverage_kind, "
      "na.repeat_context, "
      "na.compute_us, "
      "na.comm_us, "
      "na.idle_us, "
      "na.total_us, "
      "na.self_us, "
      "na.aux_events, "
      "na.aux_us "
      "FROM traceloom_viz_node_anchor na "
      "JOIN traceloom_viz_node n ON n.node_id = na.node_id "
      "AND n.db_idx = na.db_idx "
      "AND n.device_id = na.device_id "
      "AND n.view_name = na.view_name");
}

void materialize_tree_node_occurrence_view(SqliteDb& db) {
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_tree_node_occurrence AS "
      "WITH anchor_span AS ("
      "SELECT "
      "na.node_id, "
      "na.db_idx, "
      "na.device_id, "
      "na.view_name, "
      "na.occurrence_idx, "
      "MIN(a.anchor_idx) AS anchor_start_idx, "
      "MAX(a.anchor_idx) AS anchor_end_idx, "
      "COUNT(*) AS anchor_count, "
      "MIN(a.start_ns) AS start_ns, "
      "MAX(a.end_ns) AS end_ns, "
      "SUM(na.compute_us) AS compute_us, "
      "SUM(na.comm_us) AS comm_us, "
      "SUM(na.idle_us) AS idle_us, "
      "SUM(na.total_us) AS total_us, "
      "SUM(na.self_us) AS self_us, "
      "SUM(na.aux_events) AS aux_events, "
      "SUM(na.aux_us) AS aux_us, "
      "MIN(na.repeat_context) AS repeat_context "
      "FROM traceloom_viz_node_anchor na "
      "JOIN traceloom_anchor a ON a.anchor_id = na.anchor_id "
      "AND a.db_idx = na.db_idx "
      "AND a.device_id = na.device_id "
      "GROUP BY na.node_id, na.db_idx, na.device_id, na.view_name, "
      "na.occurrence_idx"
      ") "
      "SELECT "
      "a.node_id, "
      "n.local_node_id, "
      "a.db_idx, "
      "a.device_id, "
      "a.view_name, "
      "a.occurrence_idx, "
      "a.repeat_context, "
      "a.anchor_start_idx, "
      "a.anchor_end_idx, "
      "a.anchor_count, "
      "a.start_ns, "
      "a.end_ns, "
      "ROUND(COALESCE(a.compute_us, 0.0), 3) AS compute_us, "
      "ROUND(COALESCE(a.comm_us, 0.0), 3) AS comm_us, "
      "ROUND(COALESCE(a.idle_us, 0.0), 3) AS idle_us, "
      "ROUND(COALESCE(a.total_us, 0.0), 3) AS total_us, "
      "ROUND(COALESCE(a.self_us, 0.0), 3) AS self_us, "
      "COALESCE(a.aux_events, 0) AS aux_events, "
      "ROUND(COALESCE(a.aux_us, 0.0), 3) AS aux_us "
      "FROM anchor_span a "
      "JOIN traceloom_viz_node n ON n.node_id = a.node_id "
      "AND n.db_idx = a.db_idx "
      "AND n.device_id = a.device_id "
      "AND n.view_name = a.view_name");
}

void materialize_node_cost_views(SqliteDb& db) {
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_v_node_anchor_cost AS "
      "SELECT "
      "na.node_id, "
      "na.anchor_id, "
      "na.occurrence_idx, "
      "na.anchor_order, "
      "e.dur_us AS anchor_dur_us, "
      "e.role AS anchor_role, "
      "e.symbol AS anchor_symbol, "
      "e.label AS anchor_label "
      "FROM traceloom_viz_node_anchor na "
      "JOIN traceloom_anchor a ON a.anchor_id = na.anchor_id "
      "JOIN traceloom_event e ON e.event_id = a.event_id");
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_v_node_aux_cost AS "
      "SELECT "
      "na.node_id, "
      "al.anchor_id, "
      "al.aux_event_id, "
      "al.aux_order, "
      "e.dur_us AS aux_dur_us, "
      "e.role AS aux_role, "
      "e.symbol AS aux_symbol, "
      "e.label AS aux_label "
      "FROM traceloom_viz_node_anchor na "
      "JOIN traceloom_aux_link al ON al.anchor_id = na.anchor_id "
      "JOIN traceloom_event e ON e.event_id = al.aux_event_id");
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_v_node_cost AS "
      "SELECT "
      "n.*, "
      "COALESCE(anchor_cost.anchor_dur_us, 0.0) AS sql_anchor_us, "
      "COALESCE(aux_cost.aux_dur_us, 0.0) AS sql_aux_us "
      "FROM traceloom_viz_node n "
      "LEFT JOIN ("
      "SELECT node_id, SUM(anchor_dur_us) AS anchor_dur_us "
      "FROM traceloom_v_node_anchor_cost "
      "GROUP BY node_id"
      ") anchor_cost ON anchor_cost.node_id = n.node_id "
      "LEFT JOIN ("
      "SELECT node_id, SUM(aux_dur_us) AS aux_dur_us "
      "FROM traceloom_v_node_aux_cost "
      "GROUP BY node_id"
      ") aux_cost ON aux_cost.node_id = n.node_id");
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_v_node_children AS "
      "SELECT "
      "e.parent_node_id, "
      "e.child_node_id, "
      "e.edge_order, "
      "child.* "
      "FROM traceloom_viz_edge e "
      "JOIN traceloom_viz_node child ON child.node_id = e.child_node_id");
}

void materialize_tree_node_view(SqliteDb& db) {
  db.exec(
      "CREATE VIEW IF NOT EXISTS traceloom_v_tree_node AS "
      "WITH RECURSIVE tree AS ("
      "SELECT "
      "n.node_id, "
      "CAST(NULL AS TEXT) AS parent_node_id, "
      "n.db_idx, "
      "n.device_id, "
      "n.view_name, "
      "n.local_node_id, "
      "CAST(SUBSTR(n.local_node_id, 2) AS INTEGER) AS display_order, "
      "n.path, "
      "n.depth AS tree_depth, "
      "n.level AS depth, "
      "CASE WHEN n.kind = 'repeat' THEN 1 ELSE 0 END AS loop_depth, "
      "n.node_type, "
      "n.kind, "
      "n.symbol, "
      "n.label, "
      "n.category, "
      "n.repeat_label, "
      "n.repeat_count, "
      "n.occurrence_count, "
      "n.anchor_count, "
      "n.anchors_per_occurrence, "
      "n.anchors_per_occurrence AS avg_anchor, "
      "n.first_anchor_idx, "
      "n.last_anchor_idx, "
      "n.compute_us, "
      "n.comm_us, "
      "n.idle_us, "
      "n.total_us, "
      "n.avg_compute_us, "
      "n.avg_comm_us, "
      "n.avg_idle_us, "
      "n.avg_total_us, "
      "COALESCE(n.compute_us, 0.0) + COALESCE(n.comm_us, 0.0) "
      "AS active_us, "
      "ROUND((COALESCE(n.compute_us, 0.0) + COALESCE(n.comm_us, 0.0)) / "
      "CASE WHEN COALESCE(n.occurrence_count, 0) = 0 THEN 1 ELSE "
      "n.occurrence_count * CASE WHEN n.kind = 'repeat' AND "
      "COALESCE(n.repeat_count, 0) > 0 THEN n.repeat_count ELSE 1 END "
      "END, 3) AS avg_active_us, "
      "n.self_us, "
      "n.aux_events, "
      "n.aux_us, "
      "ROUND(COALESCE(n.aux_us, 0.0) / CASE WHEN "
      "COALESCE(n.occurrence_count, 0) = 0 THEN 1 ELSE "
      "n.occurrence_count * CASE WHEN n.kind = 'repeat' AND "
      "COALESCE(n.repeat_count, 0) > 0 THEN n.repeat_count ELSE 1 END "
      "END, 3) AS avg_aux_us, "
      "ROUND(CASE WHEN COALESCE(n.total_us, 0.0) = 0.0 THEN 0.0 ELSE "
      "COALESCE(n.comm_us, 0.0) / n.total_us END, 6) AS comm_pct, "
      "ROUND(CASE WHEN COALESCE(n.total_us, 0.0) = 0.0 THEN 0.0 ELSE "
      "COALESCE(n.idle_us, 0.0) / n.total_us END, 6) AS idle_pct "
      "FROM traceloom_viz_node n "
      "WHERE NOT EXISTS ("
      "SELECT 1 FROM traceloom_viz_edge e WHERE e.child_node_id = n.node_id"
      ") "
      "UNION ALL "
      "SELECT "
      "child.node_id, "
      "e.parent_node_id, "
      "child.db_idx, "
      "child.device_id, "
      "child.view_name, "
      "child.local_node_id, "
      "CAST(SUBSTR(child.local_node_id, 2) AS INTEGER) AS display_order, "
      "child.path, "
      "child.depth AS tree_depth, "
      "child.level AS depth, "
      "tree.loop_depth + CASE WHEN child.kind = 'repeat' THEN 1 ELSE 0 END "
      "AS loop_depth, "
      "child.node_type, "
      "child.kind, "
      "child.symbol, "
      "child.label, "
      "child.category, "
      "child.repeat_label, "
      "child.repeat_count, "
      "child.occurrence_count, "
      "child.anchor_count, "
      "child.anchors_per_occurrence, "
      "child.anchors_per_occurrence AS avg_anchor, "
      "child.first_anchor_idx, "
      "child.last_anchor_idx, "
      "child.compute_us, "
      "child.comm_us, "
      "child.idle_us, "
      "child.total_us, "
      "child.avg_compute_us, "
      "child.avg_comm_us, "
      "child.avg_idle_us, "
      "child.avg_total_us, "
      "COALESCE(child.compute_us, 0.0) + COALESCE(child.comm_us, 0.0) "
      "AS active_us, "
      "ROUND((COALESCE(child.compute_us, 0.0) + "
      "COALESCE(child.comm_us, 0.0)) / CASE WHEN "
      "COALESCE(child.occurrence_count, 0) = 0 THEN 1 ELSE "
      "child.occurrence_count * CASE WHEN child.kind = 'repeat' AND "
      "COALESCE(child.repeat_count, 0) > 0 THEN child.repeat_count ELSE 1 "
      "END END, 3) AS avg_active_us, "
      "child.self_us, "
      "child.aux_events, "
      "child.aux_us, "
      "ROUND(COALESCE(child.aux_us, 0.0) / CASE WHEN "
      "COALESCE(child.occurrence_count, 0) = 0 THEN 1 ELSE "
      "child.occurrence_count * CASE WHEN child.kind = 'repeat' AND "
      "COALESCE(child.repeat_count, 0) > 0 THEN child.repeat_count ELSE 1 "
      "END END, 3) AS avg_aux_us, "
      "ROUND(CASE WHEN COALESCE(child.total_us, 0.0) = 0.0 THEN 0.0 "
      "ELSE COALESCE(child.comm_us, 0.0) / child.total_us END, 6) "
      "AS comm_pct, "
      "ROUND(CASE WHEN COALESCE(child.total_us, 0.0) = 0.0 THEN 0.0 "
      "ELSE COALESCE(child.idle_us, 0.0) / child.total_us END, 6) "
      "AS idle_pct "
      "FROM tree "
      "JOIN traceloom_viz_edge e ON e.parent_node_id = tree.node_id "
      "JOIN traceloom_viz_node child ON child.node_id = e.child_node_id"
      ") "
      "SELECT * FROM tree");
}

#endif

}  // namespace traceloom::compat
